vegman: audit handling change
YADRO-KNS/obmc-yadro-cli pull request #52
Opened 2021-09-02 13:39 UTC by fr0st61te

Change the way of handling, add log_audit execution in each function
which does exact "change" system action.

Signed-off-by: Ivan Mikhaylov <i.mikhaylov@yadro.com>

2021-09-04 13:24 UTC, AlexanderAmelkin requested changes

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +  log_audit "Systime time is updated"
`Set system time to ${new_date} ${new_time//-/:}`, also this must be logged before changing the system time, not after, in order to keep the timestamp relevant.

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +    log_audit "Set parameters for remote syslog server : ${address} ${port}"
`Set remote syslog server to ${address}:${port}`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +  log_audit "Backup the BMC configuration to the file $1"
I don't think we need to log this. It doesn't change any configuration.

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +          log_audit "Manual time sync method is set"
`Changed time sync method to manual`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +          log_audit "NTP time sync method is set"
`Changed time sync method to NTP`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +  log_audit "Restore the BMC configuration from the file $1"
`Restored the BMC configuration from $1`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +  log_audit "Restore the factory default BMC config"
`Reset BMC configuration to factory defaults`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.nicole
> +  log_audit "Firmware update start"
`Firmware update start from ${fwfile}`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/bmc.vegman
> +          log_audit "Manual time sync method is set"
All comments for bmc.nicole apply here too

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/health.nicole
> +  log_audit "All logs are cleared"
Let's change to `Cleared all logs` to indicate that it was done by this user, not on its own or by someone else

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/health.vegman
> +  log_audit "All logs are cleared"
here too

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.nicole
> +  log_audit "Chassis power is switched on, host is booting up"
`Switched chassis power on, booting host`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.nicole
> +    log_audit "Chassis power is switched off, host is down"
`Switched chassis power off, host is down`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.nicole
> +    log_audit "Shutdown signal sent to host, waiting to power the system off"
`Requested host shutdown`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.nicole
> +  log_audit "Open virtual console"
`Connected to host's serial console`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Host power on"
`Switched chassis power on, booting host`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +    log_audit "Host chassis power off"
`Switched chassis power off, host is down`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +    log_audit "Host power off soft"
`Requested host shutdown`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Host power reset"
`Reset host`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Failed to mount Virtual Media (USB1)"
I don't think we need to log failed mounts to audit log.
Also, that won't do what you expect it to, need parentheses, like this:

```
<mount_command> && \
(echo "... mounted" ; log_audit "Mounted VM (USB1) from ${imagefile}") || \
echo "Failed... "
```

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Failed to unmount Virtual Media (${media})"
This again needs parentheses or it won't do what you expect.
`cmd & (success; actions) || (failure; actions)`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +    log_audit "BIOS settings will NOT be reset to defaults"
this function doesn't change anything, it only shows status. no need to log.

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Open virtual console"
`Connected to host's serial console`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/user
> +  log_audit "Create user ${name}, ${role}"
`Created ...`

2021-09-04 13:24 UTC, AlexanderAmelkin commented on commands/user
> +    log_audit "User ${name} removed"
`Removed user ${name}`

2021-09-09 07:46 UTC, alatarum approved these changes, later dismissed

2021-09-09 10:12 UTC, nest1ing commented on commands/host.vegman
> +  log_audit "Host virtual media mount : ${imagefile}") || \
It looks weird. I guess it would be better to expand this short form to a normal if-then-else statement.

2021-09-09 10:12 UTC, nest1ing commented on commands/host.vegman
> +  log_audit "Failed to unmount Virtual Media (${media})")
and here too.

2021-09-09 10:12 UTC, nest1ing commented on commands/user
> +  log_audit "Change of password for ${name}"
`passwd` may be canceled by user or fail.
I know that we are using `bash -e` and it works properly but it doesn't look obvious.
 Wouldn't it be better to join these two lines using `&&`?

2021-09-13 08:41 UTC, fr0st61te commented on commands/host.vegman
> +  log_audit "Host virtual media mount : ${imagefile}") || \
I think it's fine, @AlexanderAmelkin what do you think on this spot?

2021-09-15 09:02 UTC, AlexanderAmelkin commented on commands/host.vegman
> +  log_audit "Host virtual media mount : ${imagefile}") || \
it doesn't look weird to me, but I agree that if/else would look more clear.

2021-09-15 13:10 UTC, AlexanderAmelkin approved these changes

2021-09-15 13:10 UTC, merged