Prevent modification of admin and current user
YADRO-KNS/obmc-yadro-cli pull request #54
Opened 2021-09-08 20:11 UTC by nest1ing

This commit prevents the tries to remove or change the role of the
current user and `admin`.

Signed-off-by: Alexander Filippov <a.filippov@yadro.com>

2021-09-09 07:44 UTC, alatarum submitted a review, later dismissed

2021-09-15 08:56 UTC, AlexanderAmelkin commented
> This commit prevents the tries to remove or change the role of the

`the tries` -> `attempts`

2021-09-15 08:58 UTC, AlexanderAmelkin requested changes

2021-09-15 08:58 UTC, AlexanderAmelkin commented on commands/user
> +    echo "Admin is builtin user and cannot be removed!" >&2
`is a built-in`

2021-09-15 08:58 UTC, AlexanderAmelkin commented on commands/user
> +    echo "Admin is builtin user and cannot be changed!" >&2
same here

2021-09-15 09:17 UTC, nest1ing commented on commands/user
> +    echo "Admin is builtin user and cannot be removed!" >&2
fixed

2021-09-15 09:17 UTC, nest1ing commented on commands/user
> +    echo "Admin is builtin user and cannot be changed!" >&2
fixed

2021-09-15 09:18 UTC, nest1ing commented
> `the tries` -> `attempts`

Fixed

2021-09-15 12:29 UTC, AlexanderAmelkin approved these changes

2021-09-15 12:30 UTC, merged