Implemented functional for enable/disable/unlock users in the CLI
YADRO-KNS/obmc-yadro-cli pull request #65
Opened 2022-06-22 16:20 UTC by surf148

These functions supports multiple user names in one operation.
Function 'lock' is not implemented because lock status is calculated dynamically/

End-user-impact: Implement functional for enable/disable/unlock users in the CLI
Signed-off-by: Evgeniy Kislenok <e.kislenok@yadro.com>

2022-06-24 08:13 UTC, nest1ing approved these changes, later dismissed

2022-06-30 07:48 UTC, alatarum approved these changes, later dismissed

2022-10-13 10:53 UTC, nest1ing approved these changes, later dismissed

2022-10-19 16:20 UTC, AlexanderAmelkin requested changes
Please obey the 50/72 rule in the commit log.
Also, please use the command name in the summary, e.g.:

```
vegman: user: Add disable/enable/unlock

Implemented functions to enable/disable/unlock users in the CLI
...
```

2022-10-19 16:20 UTC, AlexanderAmelkin commented on commands/user
> +  local names=()
It's better to not combine `local` with initialization. In this particular case it doesn't make any difference, but if you cared for the completion code of the initialization, then `local` on the same line would clobber it.

Also, if you're to define an array, please use `local -a` just like you would do with `declare -a`.

2022-10-19 16:20 UTC, AlexanderAmelkin commented on commands/user
> +  local names=()
same here

2022-10-19 16:20 UTC, AlexanderAmelkin commented on commands/user
> +# enable users
Please capitalize the first letter in command descriptions

2022-10-19 16:20 UTC, AlexanderAmelkin commented on commands/user
> +# disable users
Here too

2022-10-19 17:27 UTC, AlexanderAmelkin approved these changes

2022-10-19 17:28 UTC, AlexanderAmelkin approved these changes

2022-10-19 17:28 UTC, merged