clicmd: added help for the "virtualmedia umount" utility
YADRO-KNS/obmc-yadro-cli pull request #68
Opened 2022-07-20 09:27 UTC by Smith-x86

Added virtual media device name "USB2" for the "virtualmedia
umount" utility help.

Signed-off-by: Vladimir Kuznetsov <v.kuznetsov@yadro.com>

2022-07-20 11:11 UTC, ikmsk10 submitted a review, later dismissed

2022-07-20 15:52 UTC, AlexanderAmelkin requested changes
Please update according to the latest task update.

2022-07-22 11:43 UTC, Smith-x86 commented
> Please update according to the latest task update.

Done

2022-07-22 13:46 UTC, AlexanderAmelkin approved these changes

2022-07-22 13:47 UTC, merged